version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: node:12

commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package.json" }}

  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package.json" }}
          paths:
            - ~/workspace/node_modules

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  lint:
    executor: default
    steps:
      - run: 
          name: Lint
          command: npm run lint

  build:
    executor: default
    steps:
      - run: 
          name: Build
          command: npm run build

  test:
    executor: default
    steps:
      - run: 
          name: Test
          command: npm run test:unit

  firebase:
    executor: default
    steps:
      - run: 
          name: Deploy to Firebase Hosting
          command: ls -la

workflows:
  pull-request:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - firebase:
          requires:
            - test