version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  lint:
    executor: default
    steps:
      - checkout
      - run: 
          name: Lint
          command: npm run lint

  build:
    executor: default
    steps:
      - checkout
      - run: 
          name: Build
          command: npm run build

  test:
    executor: default
    steps:
      - checkout
      - run: 
          name: Test
          command: npm run test:unit

  firebase:
    executor: default
    steps:
      - checkout
      - run: 
          name: Deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  pull-request:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - firebase:
          requires:
            - test